name: Backend Docker CI

on:
  push:
    paths: ['backend/**']
  workflow_dispatch:

jobs:
  build-docker:
    name: ğŸ³ ÄÃ³ng gÃ³i Docker Image
    runs-on: ubuntu-latest
    
    steps:
      - name: Láº¥y code vá» Runner
        uses: actions/checkout@v4

      - name: Kiá»ƒm tra phiÃªn báº£n Docker trÃªn mÃ¡y GitHub
        run: docker --version

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t app-backend:v1 .
          
      - name: Xem danh sÃ¡ch Image Ä‘Ã£ táº¡o
        run: docker images